services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.37.1
    container_name: zigbee2mqtt
    volumes:
      - zigbee2mqtt_data:/app/data
    devices:
      - /dev/${USB_DEVICE}:/dev/${USB_DEVICE}
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto:1.6.11
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mqtt_config:/mosquitto/config
      - mqtt_log:/mosquitto/log
    restart: unless-stopped

volumes:
  zigbee2mqtt_data:
    external: true
  mqtt_config:
    external: true
  mqtt_log:
    external: true
