services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.37.1
    container_name: zigbee2mqtt
    volumes:
      - zigbee2mqtt_data:/app/data
    devices:
      - /dev/${USB_DEVICE}:/dev/${USB_DEVICE}
    ports:
      - ${ZIGBEE2MQTT_WEBAPP_PORT}:8080
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto:1.6.11
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mqtt_config:/mosquitto/config
      - mqtt_log:/mosquitto/log
    restart: unless-stopped

node-red:
    image: nodered/node-red:4.0
    container_name: node-red
    environment:
      - TZ=Europe/Berlin
    ports:
      - 1880:1880
    restart: always
    volumes:
      - nodered_data:/data

volumes:
  zigbee2mqtt_data:
    external: true
  mqtt_config:
    external: true
  mqtt_log:
    external: true
  nodered_data:
    external: true
